### ISSUE TITLE
Plugin Doesn't Work

### ISSUE THREAD

**Issue by darknailblue** [somewherewarm/woocommerce-product-dependencies#3]
http://strikezone.asquaredwebsites.com/

It looks like the plugin doesnt work.  Specifically, the plugin doesn't find ANY products in the auto fill.

What should I do?

**Comment by franticpsyx** [comment]
Can't replicate any issue:

http://cl.ly/2z3i0H2Z1c1x

If you are having an issue with this plugin, the WooCommerce cross/up-sell fields shouldn't work either.

Sounds like a plugin conflict.

Please **switch back to the WordPress Twenty Fourteen Theme** and **disable all plugins except for WooCommerce (and Product Bundles)**, in order to find the plugin that causes the problem.

Thanks!
