### ISSUE TITLE
Notices do not show up for logged out users

### ISSUE THREAD

**Issue by jimjasson** [somewherewarm/woocommerce-product-dependencies#38]
### Description ###

When trying to add a product with Purchase dependencies to the cart from the Shop Archive page, then a resolution notice does not show up for logged out users. 

### Source ###

https://wordpress.org/support/topic/dependency-message-does-not-show-if-not-logged-in/

### Steps To Replicate ###

1. Create a Simple Product with a Purchase Dependency. 
2. Make sure that you are logged out.
3. Navigate to the Shop Archive page.
4. Click to add the product you previously created to the cart  -- you will be redirected to the product page but a notice won't show up. 
5. Repeat steps 3 + 4 as a logged in user.

**Comment by franticpsyx** [comment]
@jimjasson I had a look at the fix @xristos3490 came up with and we had a chat about this -- here the lowdown.

You are looking at a WooCommerce limitation here. Try the following:

- Ensure that AJAX add-to-cart in catalog archives is enabled (it is by default, as in this case).
- View a catalog page that contains a product, say "Hoodie" from a private browser window.
- Now from another, non-private browser window (of from another browser) log in and set that product's stock status to "Out of stock".
- Go back to the private window and click "add to cart".
- You will be re-directed to the product page, and no notice will show up.

What happens here is that WooCommerce cannot (should not) preserve session data across different requests -- it only does so when a session cookie has been created, which by default happens once you add some items to the cart.

To get a notice to appear, we need to create a session where we shouldn't, which could be catastrophic for servers that implement full page caching techniques.

The only real "fix" here is to disabled AJAX add-to-cart -- otherwise, you can grab this patch and modify Product Dependencies manually: https://github.com/somewherewarm/woocommerce-product-dependencies/pull/39/files (not recommended if your PHP server is behind a caching implementation).

**Comment by watou** [comment]
@franticpsyx Thank you for looking at this.  Does the observed behaviour below fit within your description of the WooCommerce limitaton?

User not logged in.  Go to a single product page with an as-yet-unsatisfied Purchase dependency.  Press the Add to Cart button.  A correct notice appears on the single product page, even though the user has not logged in.  So you are saying that the "Add to Cart" buttons on the two different kinds of pages have different-enough code paths to result in these two different outcomes?

**Comment by franticpsyx** [comment]
> So you are saying that the "Add to Cart" buttons on the two different kinds of pages have different-enough code paths to result in these two different outcomes?

@watou yes, exactly!

When clicking an AJAX add-to-cart button in a product archive, the validation notice is always lost for non-logged-in users, no matter who creates the notice. This limitation affects WooCommerce core validation notices AND all add-to-cart notices added by pretty much every plugin out there.

The notice is lost because the current user session is not maintained across the AJAX add-to-cart request and the single-product page load request. This _could_ be addressed by WooCommerce, but it would require a certain amount of creativity to avoid creating a session cookie for all subsequent page loads (doing so could overload a server that utilizes a full page cache).

**Comment by watou** [comment]
@franticpsyx Your explanation is very much appreciated!  Thank you very much for explaining the root cause of this behaviour.
