### ISSUE TITLE
Dependency not enforced once in cart

### ISSUE THREAD

**Issue by msmcguiver** [somewherewarm/woocommerce-product-dependencies#8]
This does a great job of preventing me from putting Product B in the cart unless I either own Product A, or have it in the cart.  However, if I put Product A and Product B in the cart, then remove Product A, Product B is not removed from the cart.  B should only stay in the cart if I already own A (satifying that requirement)

This seems like a gaping hole in the logic.

**Comment by franticpsyx** [comment]
Definitely needs to be fixed. Seems that a function needs to be attached to `woocommerce_check_cart_items`.

**Comment by franticpsyx** [comment]
@msmcguiver I tried what you suggest and don't see an issue, actually:

https://cl.ly/1W2g0o2x2812

When attempting to proceed to checkout:

https://cl.ly/1D1b2S2W1S27

With that said, the plugin is being refactored to add WC 2.7 compatibility, so you might want to check the latest version in `master`.

**Comment by franticpsyx** [comment]
Took another look at your issue description -- sounds like you are expecting the plugin to do something it's not supposed to. This is not a [Force Sells](https://woocommerce.com/products/force-sells/) alternative -- please read the plugin description again.

The plugin is suitable in cases where you are selling Product A that depends on Product B. It doesn't force-add Product B to the cart for you, like Force Sells does and is able to evaluate whether you have previously purchased Product B (Ownership rule), apart from requiring you to purchase B in order to get A (Purchase rule).

**Comment by franticpsyx** [comment]
Example use case: You are selling courses and wish to restrict Course B only to customers who have purchased Course A.
